apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: hola-deployment
  labels:
    app: hola-deployment
spec:
  selector:
    matchLabels:
      app: hola-deployment
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: hola-deployment
    spec:
      containers:
        - name: hola-deployment
          image: dimensionjava/billingapp-backend:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: hola-service
  labels:
    app: hola-service
spec:
  selector:
    app: hola-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
